name: Publish Docker

on:
  push:
    branches:
    - master
    tags:
    - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
  - name: Run tests
    run: ./run all --tags latest --image_name ${{ secrets.DOCKERHUB_REPO }}
  
  - name: Upload artifacts
    uses: actions/upload-artifact@v3
    with:
      name: brighton_simple
      path: results/latest/brighton_simple