name: Test ODM

on:
  push:
    branches:
    - master
    tags:
    - v*
  
  # Triggered by ODM build (after docker push)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Run tests
      run: ./run all --datasets brighton_simple --tags latest --image_name ${{ secrets.DOCKERHUB_REPO }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Brighton report.pdf
        path: results/latest/brighton_simple/test_default_with_dsm_and_dtm/odm_report/report.pdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Brighton assets
        path: |
          results/latest/brighton_simple/test_default_with_dsm_and_dtm/odm_orthophoto/
          results/latest/brighton_simple/test_default_with_dsm_and_dtm/odm_dem/
          results/latest/brighton_simple/test_default_with_dsm_and_dtm/odm_texturing/
          
          


      